apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contosopos
  namespace: contoso-supermarket
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: contosopos
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./agora/point_of_sale/operations/charts
  values:
    acr_name: 
    branch_name: "dev"
    image_tag: v1.0
    github_User: koko-bean
    queue_monitoring:
      timezone: "Pacific Standard Time"
    postgres:
      username: "postgres"
      database: "contoso"
    cosmos:
      container: "pos"
      database: "contoso"
      endpoint: 
    point_of_sale:
      title: "Contoso Supermarket"
      new_category: "True"
      holiday_banner: "False"
      store_id: 0
      store_location: "dev"
