apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-arc-windows
  namespace: hello-arc
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: hello-arc-windows
  chart:
    spec:
      chart: ./hello-arc-windows/charts/hello-arc
  values:
    image:
      repository: mcr.microsoft.com/jumpstart/arcbox/hello_arc_windows
      tag: latest
    replicaCount: 3
    env:
      name: MESSAGE
      value: Welcome to Azure Arc GitOps Demo!
